# Derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  push:
    branches: main

name: Update use_toolbox.R

jobs:
  compile:
    # if: github.event.commits[0].author.name != 'GitHubActions'
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # Use of GITHUB_TOKEN prevents infinite loops: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
      # But see https://stackoverflow.com/questions/69263843/how-to-push-to-protected-main-branches-in-a-github-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Note: no 'install dependencies' step - sticking to base R for this.
      # - name: Install dependencies
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: any::readr, any::usethis, any::devtools
      #     needs: readr, usethis, devtools

      - name: Run update
        run: source("use_toolbox/update_use_toolbox.R")
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add data/
          git add man/
          git commit -m "Update use_toolbox.R [skip actions]" || echo "No changes to commit"
          git pull --ff-only
          git push origin
